// Auto-generated by CMake & gen_ddk.py during configuration phase
// DO NOT EDIT DIRECTLY! Edit veakrnl/export.lst instead.

#ifndef _VEADDK_H_
#define _VEADDK_H_

#include <procbind.h>
#include "veadrvtype.h"

#ifdef __cplusplus
extern "C" {
#endif

VEA_EXPORT VOID VEAPI KsInitializeSpinlock(IN PKSPIN_LOCK Lock);
VEA_EXPORT VOID VEAPI KsAcquireSpinLockInternal(IN PKSPIN_LOCK Lock, OUT PKIRQL OldIrql, const PCHAR Function, const PCHAR File, INT Line);
#define KsAcquireSpinLock(Lock, Irql) KsAcquireSpinLockInternal(Lock, Irql, __FUNCTION__, __FILE__, __LINE__)
VEA_EXPORT VOID VEAPI KsReleaseSpinLockInternal(IN PKSPIN_LOCK Lock, IN KIRQL OldIrql, const PCHAR Function, const PCHAR File, INT Line);
#define KsReleaseSpinLock(Lock, Irql) KsReleaseSpinLockInternal(Lock, Irql, __FUNCTION__, __FILE__, __LINE__)
VEA_EXPORT VEASTATUS VEAPI ObioGoInterruptObject( PVOID TargetObject, POIP Oip );
VEA_EXPORT VEASTATUS VEAPI ObioCreateDriver( PCHAR DriverName, PDRIVER_INITIALIZE InitializationFunction, OUT PDRIVER_OBJECT *DriverObject );
VEA_EXPORT VEASTATUS VEAPI ObioCreateNewDevice( PDRIVER_OBJECT DriverObject, ULONG DeviceExtSize, PCHAR DeviceName, ULONG DeviceType, PDEVICE_OBJECT *NewDevice );
VEA_EXPORT VOID KdPrintf(const char *Format, ...);
VEA_EXPORT PVOID VEAPI UlAllocatePoolWithTag(POOL_TYPE PoolType, ULONG NumberOfBytes, ULONG Tag);
VEA_EXPORT VOID VEAPI UlFreePoolWithTag(PVOID P, ULONG Tag);
VEA_EXPORT PVOID VEAPI UlAllocatePoolZero(POOL_TYPE PoolType, ULONG NumberOfBytes, ULONG Tag);
VEA_EXPORT BOOLEAN VEAPI RtlUnicodeStringToAnsiString( PANSI_STRING DestinationString, const UNICODE_STRING *SourceString, BOOLEAN AllocateDestinationString );
VEA_EXPORT VOID VEAPI RtlInitAnsiString( PANSI_STRING DestinationString, const PCHAR SourceString );
VEA_EXPORT VOID VEAPI RtlInitUnicodeString( PUNICODE_STRING DestinationString, const PWCHAR SourceString );
VEA_EXPORT BOOLEAN VEAPI RtlAnsiStringToUnicodeString( PUNICODE_STRING DestinationString, const ANSI_STRING *SourceString, BOOLEAN AllocateDestinationString );

#ifdef __cplusplus
}
#endif

#endif // _VEADDK_H_
